version: "3"

services:
  db:
   container_name: fabriquepollgres
   image: postgres
   restart: always
   environment:
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=dev
    - POSTGRES_DB=fabrique_polls
   ports:
    - '5432:5432'
  apiserver:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
