# Generated by Django 3.1.5 on 2021-01-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.UUIDField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('poll', 'question', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('poll', 'question_text')},
        ),
    ]
